### ISSUE TITLE
No longer access vault 

### ISSUE THREAD

**Issue by ssoriche** [dasilva333/DIM#20]
I see my 3 characters but do not see the vault. Following error in the Javascript Console:

```
app.js:636 Uncaught TypeError: Cannot read property 'itemName' of undefined
```

I've heard other people have the same issue.

**Comment by dasilva333** [comment]
Thanks man if you could also include a screenshot of your vault from DIM or otherwise that would help too. You probably have some item I don't so I haven't caught the bug. I'll be adding a temporary fix to stop it from working but I can't guarantee it'll fix the root issue. Look for version 1.3.7 in the div-movile-dist branch for Chrome to try the fix. Thanks again

**Comment by dasilva333** [comment]
Heres the link in case you can't find it: https://github.com/dasilva333/DIM/blob/div-movile-dist/destiny_item_viewer.zip

**Comment by DeCoded-Void** [comment]
Do you by any chance have the 4th horseman in your vault?

**Comment by ssoriche** [comment]
Yes, I just moved it there. Was just about to add a link to the image — https://i.imgur.com/GcpgXGC.png <https://i.imgur.com/GcpgXGC.png>

**Comment by DeCoded-Void** [comment]
I am unable to access 2/3 of my characters since they have the 4th horseman in the inventory in both of my characters, you can read what I said here: https://github.com/dasilva333/DIM/issues/19

**Comment by Mulchman** [comment]
Think this can be closed now; fixed in #25

**Comment by dasilva333** [comment]
Problem fixed you should see the 4th horseman now update to the latest version

**Comment by ssoriche** [comment]
I can see my vault and characters but the 4th Horsemen does not show at all with 1.5.1. The official app just shows Classified.
