### ISSUE TITLE
Show Actual Values vs. Theoretical Values?

### ISSUE THREAD

**Issue by seansli** [dasilva333/DIM#32]
Is there any way to show the actual value of light/stat for an item, instead of just the possible values? in TDG, hovering over [an item](https://www.dropbox.com/s/bqdx24fhfalqc8x/Screenshot%202015-04-06%2015.20.20.png) gives you all possible rolls, instead of the roll for your specific weapon. Optimally, it'd be best to have the in-game showing where it gives you current/max.

On a different note, some of the values appear off for the weapons. This [LDR](https://www.dropbox.com/s/jgmcit6zurjc6c5/Screenshot%202015-04-06%2015.21.19.png), for example, shows a max of 350 attack, which is impossible.

**Comment by wickles** [comment]
I don't think the API allows for actual max values. The Bungie website itself only shows current values AFAIK. I believe the extension just pulls theoretical values from DestinyDB (which has some inaccuracies as you've found), since there doesn't seem to be any other way to get the correct data.

**Comment by dasilva333** [comment]
@seansil for the deathsinger's grip the tooltip is working as expect, it's showing you those gauntlets have 51 int and 52 strength and showing u the min/max values provided by DestinyDB. Regarding the max attack value of the LDR that's information from DestinyDB they mess up some items because of the HoW data that's incoming. Wickles summarized it pretty well regarding the inaccuracies but indeed the tooltip shows both actual and theoretical values. Closing ticket no issue found.
