### ISSUE TITLE
Request:  Tap top of screen/clock to scroll to top

### ISSUE THREAD

**Issue by DrPippin** [dasilva333/DIM#51]
I'd like to request functionality where you tap at the top of the screen (clock) on iOS devices to scroll to the top.  It's become an automatic behavior for me due to fairly ubiquitous implementation throughout iOS apps, that I still find myself trying to use it in TGD.

**Comment by dasilva333** [comment]
Two things, 1. great suggestion 2. mind blown I didn't even know I could do that with my iPhone I then proceeded to try it on every app I use, thanks man

**Comment by ssoriche** [comment]
I’ve got code to do it already. Will check it in shortly.

~Shawn

**Comment by dasilva333** [comment]
Problem fixed in 1.9.0 thanks guys please confirm

**Comment by DrPippin** [comment]
Just updated to 1.9.0, and it is not working.

**Comment by DrPippin** [comment]
Just updated to 1.9.2. The first time the phone is in landscape view tapping at the top of the screen works appropriately to take you back to the top. But in portrait view tapping at the top doesn't work at all. And the second time landscape view is accessed tapping at the screen doesn't work (eg. Load in portrait and tapping doesn't work, go to landscape and tapping works, go back to portrait and tapping doesn't work, go back to landscape and tapping doesn't work).

**Comment by DrPippin** [comment]
1.9.3 still has the same behavior as I outlined for 1.9.2.

**Comment by DrPippin** [comment]
1.9.7 still has the same functionality I outlined above.

**Comment by dasilva333** [comment]
@DrPippin thanks man I haven't tried to revisit a solution after my initial fix I'll be looking into a solution for getting it to work all the time and let you know when to test again thanks man

**Comment by dasilva333** [comment]
So I figured out the reason the tap doesn't work as expected, it turns out that because I package my apps with the adobe updater they override the tap events for the sake of updating the app. You can see the non-hydrated 1.9.7 works properly:

https://github.com/dasilva333/TowerGhostForDestiny/blob/div-movile-dist/TowerGhostforDestiny_v197.ipa

Closing ticket as this is something I won't/can't fix due to the updater it's being packaged with. Also please remember to post any future issues in the new repo. Thanks

**Comment by DrPippin** [comment]
Makes sense. I'll try the non-hydrated version for completeness sake just to be sure it's working on my phone, too. And sorry for using this repo. Didn't realize there was a new one.
